### ISSUE TITLE
Image compatibility

### ISSUE THREAD

**Issue by terryvi** [MadLittleMods/gulp-css-spriter#4]
hello~ uh, I try this plugin to make a spriter pic. but, gulp throw an error message: error creating sprite sheet image :unsupported interlace method.  finally( about 2 hours later hahahah),I import some png with AI instead of PS. This plugin runs successful. So er... my question is ：Is PS‘s image algorithm make gulp-css-spriter  throw such error message?

**Comment by MadLittleMods** [comment]
@terryvi It shouldn't, I used a bunch of [Photoshop PNG with `gulp-css-spriter` here](https://github.com/MadLittleMods/crispin-mulberry-fe-nat/blob/04610a7122fe58dcb73442f38117cf6d4f3d05d1/gulp/tasks/sass-tasks.js#L15).

The [error you are getting has to do with the `spritesmith`, spritesheet build](https://github.com/MadLittleMods/gulp-css-spriter/blob/c8b2ccb543ede1a55386e4d2cf138984b3745a42/index.js#L277) so perhaps it is an issue with spritesmith itself.

**Comment by terryvi** [comment]
Okay,thx。
